name: Java Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Get Last Commit Message
        id: get-commit-message
        run: |
          git log --pretty=format:'%B' -n 3 > commit_message.txt
          echo "COMMIT_MESSAGE=$(cat commit_message.txt)" >> $GITHUB_ENV
      - name: Build Description
        run: |
          echo "Deployment Description: ${{ env.COMMIT_MESSAGE }}"
      - name: Upload JAR Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: built-jars
          path: target/*.jar  # Replace with the path to your JAR files
          # Use the environment variable in the description
          description: "Built from ${{ env.COMMIT_MESSAGE }}"
