name: Java Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Get Last Commit Message
        id: get-commit-message
        run: |
          git log --pretty=format:'%B' -n 1 > commit_message.txt
          echo "COMMIT_MESSAGE=$(cat commit_message.txt)" >> $GITHUB_ENV
      - name: Set Environment Variables
        run: |
          echo 'GAME_VERSIONS=["1.18.1", "1.19", "1.20"]' >> $GITHUB_ENV
      - name: Generate AI-Based README for Version Change
        id: generate-readme
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          COMMIT_MESSAGE: ${{ env.COMMIT_MESSAGE }}
        run: |
          RESPONSE=$(curl -s -X POST https://api.openai.com/v1/chat/completions \
            -H "Authorization: Bearer $OPENAI_API_KEY" \
            -H "Content-Type: application/json" \
            -d '{
              "model": "gpt-3.5-turbo",
              "messages": [
                {
                  "role": "system",
                  "content": "Generate a release note for a software project based on the following commit message. The release note should be written in readme format."
                },
                {
                  "role": "user",
                  "content": "The commit message for the release note: \"${COMMIT_MESSAGE}\""
                }
              ]
            }')
          echo "$RESPONSE" | jq -r '.choices[0].message.content' > README.md
      - name: Upload Bukkit JAR Artifacts
        uses: actions/upload-artifact@v4.3.3
        with:
          name: built-bukkit-jar
          path: Bukkit/target/*.jar
      - name: Upload Velocity JAR Artifacts
        uses: actions/upload-artifact@v4.3.3
        with:
          name: built-velocity-jar
          path: Velocity/target/*.jar
      - name: Download Bukkit JAR Artifact
        uses: actions/download-artifact@v4
        with:
          name: built-bukkit-jar
          path: ./downloaded/bukkit
      - name: Download Velocity JAR Artifact
        uses: actions/download-artifact@v4
        with:
          name: built-velocity-jar
          path: ./downloaded/velocity
      - name: Upload Bukkit JAR to Modrinth
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          GAME_VERSIONS: ${{ env.GAME_VERSIONS }}
          COMMIT_MESSAGE: ${{ env.COMMIT_MESSAGE }}
        run: |
          JAR_FILE=$(find ./downloaded/bukkit -name "*.jar")
          VERSION_NUMBER="v${{ github.run_number }}"
          PROJECT_ID="wIuI4ru2"
          README_CONTENT=$(jq -Rs . < README.md)
          
          curl --http1.1 -X POST https://api.modrinth.com/v2/version \
            -H "Authorization: Bearer $MODRINTH_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{
              "name": "Bukkit Release '"$VERSION_NUMBER"'",
              "version_number": "'"$VERSION_NUMBER"'",
              "changelog": "'"$COMMIT_MESSAGE"'",
              "game_versions": '"$GAME_VERSIONS"',
              "dependencies": [],
              "project_id": "'"$PROJECT_ID"'",
              "loaders": ["fabric", "forge"],
              "files": [
                {
                  "hashes": {
                    "sha512": "'"$(sha512sum $JAR_FILE | awk '{ print $1 }')"'
                  },
                  "url": "'"file://$JAR_FILE"'",
                  "filename": "'"$(basename $JAR_FILE)"'"
                }
              ],
              "description": '"$README_CONTENT"',
              "version_type": "release",
              "status": "listed",
              "requested_status": "listed"
            }'
      - name: Upload Velocity JAR to Modrinth
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          GAME_VERSIONS: ${{ env.GAME_VERSIONS }}
          COMMIT_MESSAGE: ${{ env.COMMIT_MESSAGE }}
        run: |
          JAR_FILE=$(find ./downloaded/velocity -name "*.jar")
          VERSION_NUMBER="v${{ github.run_number }}"
          PROJECT_ID="wIuI4ru2"
          README_CONTENT=$(jq -Rs . < README.md)
          
          curl --http1.1 -X POST https://api.modrinth.com/v2/version \
            -H "Authorization: Bearer $MODRINTH_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{
              "name": "Velocity Release '"$VERSION_NUMBER"'",
              "version_number": "'"$VERSION_NUMBER"'",
              "changelog": "'"$COMMIT_MESSAGE"'",
              "game_versions": '"$GAME_VERSIONS"',
              "dependencies": [],
              "project_id": "'"$PROJECT_ID"'",
              "loaders": ["fabric", "forge"],
              "files": [
                {
                  "hashes": {
                    "sha512": "'"$(sha512sum $JAR_FILE | awk '{ print $1 }')"'
                  },
                  "url": "'"file://$JAR_FILE"'",
                  "filename": "'"$(basename $JAR_FILE)"'"
                }
              ],
              "description": '"$README_CONTENT"',
              "version_type": "release",
              "status": "listed",
              "requested_status": "listed"
            }'
