name: Java Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Get Last Commit Message
        id: get-commit-message
        run: |
          git log --pretty=format:'%B' -n 1 > commit_message.txt
          echo "COMMIT_MESSAGE=$(cat commit_message.txt)" >> $GITHUB_ENV
      - name: Set Environment Variables
        run: |
          echo 'GAME_VERSIONS=["1.18.1", "1.19", "1.20"]' >> $GITHUB_ENV
      - name: Generate AI-Based README for Version Change
        id: generate-readme
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          COMMIT_MESSAGE: ${{ env.COMMIT_MESSAGE }}
        run: |
          RESPONSE=$(curl -s -X POST https://api.openai.com/v1/chat/completions \
            -H "Authorization: Bearer $OPENAI_API_KEY" \
            -H "Content-Type: application/json" \
            -d '{
              "model": "gpt-3.5-turbo",
              "messages": [
                {
                  "role": "system",
                  "content": "Generate a release note for a software project based on the following commit message. The release note should be written in readme format."
                },
                {
                  "role": "user",
                  "content": "The commit message for the release note: \"${COMMIT_MESSAGE}\""
                }
              ]
            }')
          echo "$RESPONSE" | jq -r '.choices[0].message.content' > README.md
      - name: Upload Bukkit JAR Artifacts
        uses: actions/upload-artifact@v4.3.3
        with:
          name: built-bukkit-jar
          path: Bukkit/target/*.jar
      - name: Upload Velocity JAR Artifacts
        uses: actions/upload-artifact@v4.3.3
        with:
          name: built-velocity-jar
          path: Velocity/target/*.jar
      - name: Download Bukkit JAR Artifact
        uses: actions/download-artifact@v4
        with:
          name: built-bukkit-jar
          path: ./downloaded/bukkit
      - name: Download Velocity JAR Artifact
        uses: actions/download-artifact@v4
        with:
          name: built-velocity-jar
          path: ./downloaded/velocity
      - name: List Downloaded Files
        run: |
          echo "Downloaded files in ./downloaded/bukkit:"
          ls -la ./downloaded/bukkit
          echo "Downloaded files in ./downloaded/velocity:"
          ls -la ./downloaded/velocity
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release v${{ github.run_number }}
          body: ${{ env.COMMIT_MESSAGE }}
          draft: false
          prerelease: false
      - name: Upload Bukkit JAR to GitHub Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./downloaded/bukkit/CommandBridgeBukkit-1.3-SNAPSHOT.jar
          asset_name: CommandBridgeBukkit-${{ github.run_number }}.jar
          asset_content_type: application/java-archive
      - name: Upload Velocity JAR to GitHub Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./downloaded/velocity/CommandBridgeVelocity-1.3-SNAPSHOT.jar
          asset_name: CommandBridgeVelocity-${{ github.run_number }}.jar
          asset_content_type: application/java-archive
      - name: Upload Bukkit JAR to Modrinth
        uses: cloudnode-pro/modrinth-publish@1.0.0
        with:
          token: ${{ secrets.MODRINTH_TOKEN }}
          project_id: wIuI4ru2
          version_number: v${{ github.run_number }}
          version_name: Bukkit Release v${{ github.run_number }}
          changelog: ${{ env.COMMIT_MESSAGE }}
          game_versions: ${{ env.GAME_VERSIONS }}
          file_path: ./downloaded/bukkit/CommandBridgeBukkit-1.3-SNAPSHOT.jar
          version_type: release
          loaders: '["bukkit"]'
          dependencies: '[]'
      - name: Upload Velocity JAR to Modrinth
        uses: cloudnode-pro/modrinth-publish@1.0.0
        with:
          token: ${{ secrets.MODRINTH_TOKEN }}
          project_id: wIuI4ru2
          version_number: v${{ github.run_number }}
          version_name: Velocity Release v${{ github.run_number }}
          changelog: ${{ env.COMMIT_MESSAGE }}
          game_versions: ${{ env.GAME_VERSIONS }}
          file_path: ./downloaded/velocity/CommandBridgeVelocity-1.3-SNAPSHOT.jar
          version_type: release
          loaders: '["velocity"]'
          dependencies: '[]'
