name: Java Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Get Last Commit Message
        id: get-commit-message
        run: |
          git log --pretty=format:'%B' -n 3 > commit_message.txt
          echo "COMMIT_MESSAGE=$(cat commit_message.txt)" >> $GITHUB_ENV
      - name: Build Description
        run: |
          echo "Deployment Description: ${{ env.COMMIT_MESSAGE }}"
      - name: Upload Bukkit JAR Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: built-bukkit-jar
          path: Bukkit/target/*.jar
      - name: Upload Velocity JAR Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: built-velocity-jar
          path: Velocity/target/*.jar