name: Upload to Modrinth

on:
  release:
    types: [created]

jobs:
  upload-to-modrinth:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Get Release Assets URLs
        id: get-release-assets
        run: |
          release_url="https://api.github.com/repos/${{ github.repository }}/releases/tags/${{ github.event.release.tag_name }}"
          assets=$(curl -s -H "Authorization: token ${{ secrets.PAT_TOKEN }}" $release_url | jq -r '.assets[] | select(.name | test("CommandBridgeBukkit|CommandBridgeVelocity")) | .browser_download_url')
          echo "$assets" > assets_urls.txt
          echo "ASSET_URLS=$(cat assets_urls.txt)" >> $GITHUB_ENV

      - name: Set Environment Variables for Bukkit and Velocity
        run: |
          while read -r line; do
            if [[ $line == *"CommandBridgeBukkit"* ]]; then
              echo "BUKKIT_ASSET_URL=$line" >> $GITHUB_ENV
            elif [[ $line == *"CommandBridgeVelocity"* ]]; then
              echo "VELOCITY_ASSET_URL=$line" >> $GITHUB_ENV
            fi
          done < assets_urls.txt

      - name: Upload Bukkit JAR to Modrinth
        uses: cloudnode-pro/modrinth-publish@1.0.0
        with:
          token: ${{ secrets.MODRINTH_TOKEN }}
          project: wIuI4ru2
          changelog: ${{ github.event.release.body }}
          file: ${{ env.BUKKIT_ASSET_URL }}
          loaders: '["bukkit"]'
          dependencies: '[]'

      - name: Upload Velocity JAR to Modrinth
        uses: cloudnode-pro/modrinth-publish@1.0.0
        with:
          token: ${{ secrets.MODRINTH_TOKEN }}
          project: wIuI4ru2
          changelog: ${{ github.event.release.body }}
          file: ${{ env.VELOCITY_ASSET_URL }}
          loaders: '["velocity"]'
          dependencies: '[]'
