name: CommandBridge
version: 2.2.2
main: dev.consti.commandbridge.paper.Main
author: 72-S
api-version: '1.20'
folia-supported: true
dependencies:
  server:
    PlaceholderAPI:
      load: BEFORE
      required: false
